[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve -s dist"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments]
NODE_ENV = "production"
